language: java
jdk:
  - oraclejdk8
script: mvn verify cobertura:cobertura -B

sudo: required

services:
  - docker

before_install:
- docker pull mongo
- docker run -d -p 127.0.0.1:27017:27017 mongo

after_success:
  - bash <(curl -s https://codecov.io/bash)